### ISSUE TITLE
Control and form colors appear to randomly change during export/build

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#183]
I've noticed that the exported colors appear to randomly change, even if they appear correctly in the form. This seems to be especially prevalent when using themes to map colors.

**Comment by hecon5** [comment]
I should clarify: I mean the exported code color changes; I do not notice any change in the actual displayed color on the Form/Reports.

**Comment by hecon5** [comment]
@joyfullservice; this probably should go to a discussion, as it's an over-arching concept, and might not affect anything, but could inform new development work ongoing.

**Comment by hecon5** [comment]
I commented on and closed the wrong issue...gah.

**Comment by A9G-Data-Droid** [comment]
Here is a discussion that offers an explanation:
https://stackoverflow.com/questions/4608167/color-constants-in-access-2007

**Comment by joyfullservice** [comment]
Looking at the source behind a form control, it appears that the `BorderColor` property contains everything Access needs to know about the color...

![image](https://user-images.githubusercontent.com/7254992/110154166-8d63b900-7da9-11eb-8a5e-c37465dd1964.png)

Perhaps it tries to match it against the theme color schemes and shade variants first, and if it matches, it shows the theme color, but if no match is found, it just displays the [actual color](https://officetricks.com/convert-excel-vba-color-codes-rgb-hex/)...

**Comment by hecon5** [comment]
The BackColor does this, too. An example (button) with a theme:
I'm actually not 100% certain how this works, t
![image](https://user-images.githubusercontent.com/54177882/110155115-22b77b00-7db3-11eb-9c33-bd183330561b.png)

**Comment by joyfullservice** [comment]
Thank you all for the good input on this! I think I will go ahead and close out this issue since **it does not appear to be practically feasible** to standardize these values across different systems.

**Comment by joyfullservice** [comment]
I came across a clue today that gives me a glimmer of hope that we may actually be able to solve this! It is not a trivial change, but my hunch is that we could ultimate resolve this problem through the sanitize function/class.

Here is the gist of the idea. If you look at the examples above, or other examples in your own projects, you will see that on the controls where the color values are changing, they are also using a theme **color index**, **tint** and **shade**.

![image](https://user-images.githubusercontent.com/7254992/120715505-4b224480-c48a-11eb-8994-b2cb3aa7f9a6.png)

My hunch is that when _**theme color index**_ is used, the color value is simply representative, based on the graphics/monitor setup on that computer. The first time the form is opened, the actual color is calibrated for the system and updated. That's why you will see this value change between exports, depending on whether or not you have opened the form since importing it. Perhaps the color (placeholder?) exists just in case the theme definition is not found, so Access can at least somewhere close in representing the color. (That part is pure conjecture.)

When I compare this to other color values that _don't_ change between exports, I find that the colors that don't change are the ones that are using absolute color values, not theme _index/tint/shade_. For these, the theme index is set to `-1`.

![image](https://user-images.githubusercontent.com/7254992/120716622-ea940700-c48b-11eb-9e73-bb232a1cdea5.png)

My hypothesis is that we could take one of the two following approaches to standardize the export files and resolve this issue:

1. **Discard the placeholder color value**, since this will be dynamically generated automatically. If this doesn't create any errors on import, and doesn't cause any changes to the color, this would be the preferred option.
2. If the above doesn't work, a second approach would be to **compute the placeholder value ourselves** in a way that is generically consistent between systems. This would be more involved because it would mean extracting and parsing the theme xml file to determine the actual color values of the theme index, and factor in the tint and shade, but is still technically possible.

With either approach we will need to use a more sophisticated parsing function because we need to link these related lines to determine what to do with the color value line. (Keep it, discard it, or compute it ourselves.) We would need to read all the property lines for the control before we could make the determination, and multiple properties of the control involve color values. It would probably need a two-pass approach where we read all the lines first, then make any adjustments before writing the finalized control block section.

While this is obviously not a quick and simple fix, it does seem like there is a good possibility that this will allow us to ultimately resolve the issue with unwanted change noise appearing in source files between builds, caused by theme-based automatically generated color values.

If anyone has opportunity to do some more research/testing/development on this idea, please post your findings here!  😄

**Comment by hecon5** [comment]
It's funny, I was raging at Access's color functions today, too; for a similar issue: Themes. 

I posted it on this [SO Theme question ](https://stackoverflow.com/questions/67822340/access-setting-theme-vba-using-msothemecolorschemeindex-is-off-by-1), if you have any ideas, but for now I like your thoughts.

FWIW, I don't think option 1 will work, because I've noticed with custom themes set, I have to close and then reopen the Access file for the theme to be "respected". Once I do this, it works flawlessly. That said...you might be onto something. I'll do some quick and dirty testing and see what happens.

**Comment by hecon5** [comment]
Update: it turns out... Option 1 might actually work! 

I deleted a bunch of color definitions from fields, and it imported fine! This ... could be very promising!

Now to determine how best to do the sanitize (should this be integral to `clsDbForm` or part of the `modSanitize`? My thoughts are that probably best in `modSanitize`, though you raise an interesting idea for a whole sanitize class, cleaner code, but implementation would be more difficult.

**Comment by A9G-Data-Droid** [comment]
I agree. I think option 1 is best. Unfortunately I'm not seeing a clear pattern that relates the name of the theme and the associated color definitions. We might have to build a dictionary that maps them so that dictionary can be looped. Ugh.

**Comment by joyfullservice** [comment]
@hecon5 - Thanks for the update! That does sound very encouraging!

After thinking through the implementation details this morning, I think you are right that `modSanitize` is probably the best place to implement this, inline with the other sanitizing code. Unfortunately it does add some complexity to the function, since we can't just loop through the lines and make the keep or discard decision on the first pass, like we do now.

Since performance is very crucial in this function, I am thinking that the best way to do this is to loop through all the lines like we currently do, but instead of building the new file contents at the same time, we would instead be building an _array of line numbers_ that we want to _exclude_ from the new file. The first pass would involve all the logic of making those decisions of what to include and what to discard.

We would then sort the array of lines to exclude so that on the second pass through the lines of the file we could also incrementally iterate through the lines to exclude as we build the actual file contents using the concatenation class. This allows us to use very lightweight numerical comparisons with the array and avoid unnecessary loops. Taking this approach, I think the performance would be very similar to the current highly optimized function.

Adding to the complexity here is that I believe control definition blocks can be nested, requiring us to use a call-stack type of concept to ensure that we are linking the line of the `*ColorIndex` to the `*Color` of the same control. (Since the two might be on either side of another nested definition block) This should be manageable using nested dictionaries relative to the indent position in the file. When we reach the `end` of a section definition, we would then make the determination on which `*Color` lines should be discarded, and remove the dictionary that represents that section.

**Comment by joyfullservice** [comment]
> 
> 
> I agree. I think option 1 is best. Unfortunately I'm not seeing a clear pattern that relates the name of the theme and the associated color definitions. We might have to build a dictionary that maps them so that dictionary can be looped. Ugh.

Would this even matter if we are taking option 1 and simply discarding the lines with the color definitions? Or maybe I am missing something here...  🤔

**Comment by A9G-Data-Droid** [comment]
@joyfullservice are you talking about always dropping color definitions? Or only dropping definitions when the associated theme index is -1 ? Maybe I misunderstood.

**Comment by joyfullservice** [comment]
> 
> 
> @joyfullservice are you talking about always dropping color definitions? Or only dropping definitions when the associated theme index is <> -1 ? Maybe I misunderstood.

Correct. I am looking at only dropping them if the `*ColorIndex` is <> `-1`. (As shown in the top example of the image I posted yesterday.)

**Comment by A9G-Data-Droid** [comment]
So you need to first establish the relationship between the related entries. Maybe this could be done with an access table? Then for each index that is <> -1 remove related lines. If the lines were split on the `=` character then you could do a quick lookup on the LHS of the `=` to get the line number. Then remove those lines from the line collection.

**Comment by joyfullservice** [comment]
@A9G-Data-Droid - Yes, that's the general idea. Establish the relationship between the lines, and remove the color line if the ThemeColorIndex is <> -1. I am thinking that a dictionary is going to be more performant than a table, especially since it has the `Exists` function to quickly locate a key.

For example, if I was looping through the lines, and found `ForeColor =12673797`, I would add this to a dictionary object with `ForeColor` as the key, and the line number as the value. Then later in the same section, if I found `ForeThemeColorIndex =10` then I would know that I can discard the ForeColor line. If I found the first dictionary entry, I would add this line number as a line to exclude in the final output file.

**Comment by hecon5** [comment]
Two things: It appears it's not just "me" with the off by one issue, `-1` is technically undefined, and[ `msoNotThemeColor = 0`](https://docs.microsoft.com/en-us/office/vba/api/office.msothemecolorindex). Whatever. I digress; that's cost me enough headache this week. 

I also have these in some of my forms:

```VBA
 DatasheetBackThemeColorIndex
 DatasheetGridlinesColorThemeColorIndex
```

Which makes me wonder, instead of trying to ensure we have a complete list, would it be more accurate to match against `"ThemeColorIndex"` and then see if the right of that string is `" =-1"` or not?

This would ensure we don't need to know all the possibilities (seems like we're still missing some).

**Comment by A9G-Data-Droid** [comment]
Yeah you could write a generic `<= 0` based test but which lines would you omit for each ThemeColorIndex? 

Would you just remove "ThemeColorIndex" and wildcard match against the prefix? I guess we would have to see if that pattern is consistent.

**Comment by hecon5** [comment]
I'm not sure we want to do a generic `<=0` test...I see there's a `msoThemeColorMixed "-2"`, which leads me to think that the `msoNotThemeColor ` (`-1`) should probably be a constant we can change if and when MSFT ever fixes this oddity; and that there's a chance that whatever `msoThemeColorMixed` is might mean we don't want to remove those colors.

**Comment by joyfullservice** [comment]
What I am seeing is that you could probably replace `ThemeColorIndex` with `Color` to set the base color. I like that idea of simplifying the comparison, but I did notice one property that seemed inconsistent with the others:

![image](https://user-images.githubusercontent.com/7254992/120852806-53d55200-c540-11eb-8c63-bd69ee15df64.png)

@hecon5 - Were you indicating that this was coming through as `DatasheetGridlinesColorThemeColorIndex` on your system?

**Comment by hecon5** [comment]
I'm not sure we want to do a generic `<=0` test...I see there's a `msoThemeColorMixed "-2"`, which leads me to think that the `msoNotThemeColor ` (`-1`) should probably be a constant we can change if and when MSFT ever fixes this oddity; and that there's a chance that whatever `msoThemeColorMixed` is might mean we don't want to remove those colors.

In terms of what we should remove (red is removal, green is "kept").

```DIFF
' For values that have a theme:  ([Border] = [ColorName] Below)
-- BorderColor =16777215
++ BorderThemeColorIndex =2
++ BorderTint =60.0

' For controls/components that don't use a theme: ([HoverFore] = [ColorName] Below)
++  HoverForeColor =0
++  HoverForeThemeColorIndex =-1
```

More generically, for a given `[ColorName]` `[Color]`, delete the matching `[Color]` line where the `[ColorName]` `[ThemeColorIndex]` `=-1`

@joyfullservice yes, on a few forms; not often, but it's there, and if I change it, it does affect the form look.

**Comment by hecon5** [comment]
What I see is:

```VBA
   DatasheetGridlinesColor =15132391
 
    <Buncha unrelated field info like you have>

    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    <more stuff>
```

**Comment by joyfullservice** [comment]
I think we are getting pretty close! Do you want to try this on some of your projects? I have made some additional enhancements to support the behavior where a control block may not have a `*ThemeColorIndex` line in the export file if the control is using the default theme color index for the control.

For example, the `cmdCancel` button in `frmVCSInstall` uses theme colors for all of the button properties:

![image](https://user-images.githubusercontent.com/7254992/120863746-a9b1f600-c550-11eb-8ede-869b93a84ef5.png)

However, the export file does not show any ThemeColorIndex values for these. Only the colors themselves.

![image](https://user-images.githubusercontent.com/7254992/120864506-efbb8980-c551-11eb-899d-d31c250b34a2.png)

Notice that if I change a color index to use another index, (or another non-theme color) then the index line appears!

![image](https://user-images.githubusercontent.com/7254992/120864691-38734280-c552-11eb-9098-3d585aa008e7.png)

![image](https://user-images.githubusercontent.com/7254992/120864755-5476e400-c552-11eb-9273-f3a01a9dc641.png)

Now see what happens when we change this to a non-theme color:

![image](https://user-images.githubusercontent.com/7254992/120864865-8a1bcd00-c552-11eb-9103-a83089eb468a.png)

The `BorderColor` property line is added, and the `BorderThemeColorIndex` is set to `-1`, just like we would expect. With the latest updates, the code should correctly handle these situations where default theme index values are being used on certain controls.

Let me know how this works in your testing!  😄

**Comment by A9G-Data-Droid** [comment]
Using dev branch: Full export ran in 36.07 seconds and no files changed.
Using SanitizeDynamicThemeColors 36.23 seconds and no files changed.

The problem is that build from source isn't doing anything. It runs and it displays the "Build Complete" message but the version control DB file doesn't change. The version number stays at 3.3.17 and the modules in the DB don't match the source files I just built from. I can see the new code in the source files so my branch is pulling the update. Not sure what is going on. Can you release a development version?

**Comment by joyfullservice** [comment]
Sure, give me a few minutes to put that together...

**Comment by A9G-Data-Droid** [comment]
@joyfullservice I did a step through of the build process to see where the problem is. I'm opening a development version of the add-in, and running build. It closes the development version and then begins building using the installed add-in. The installed add-in doesn't have a source folder, so it fails to find any source files.

I'm not sure why this is happening. I haven't changed my process. It used to build from the source of the development version, not the installed add-in. I hope that makes sense.

I tried running the build from the development version and it says I need to run build from the installed add-in, which is not working as it used to:
![image](https://user-images.githubusercontent.com/26984068/121059136-f88ca500-c775-11eb-9bb0-ad3c27f15ff6.png)

**Comment by A9G-Data-Droid** [comment]
The problem has to do with it trying to find the source folder. So I manually set the folder in the options. Now I get 

`Source: modImportExport.Build Error 2950: Reserved Error`

for every source file.

**Comment by joyfullservice** [comment]
Attached is a beta version built from the `SanitizeDynamicThemeColors` branch. You should be able to use this to build the `SanitizeDynamicThemeColors` branch. It won't build the `dev` branch right now because the `dev` branch has been migrated over to use the `*.cls` extension for class modules. I didn't pull over the new file extension change to this branch yet because I wanted to be able to do some testing to make sure the colors issue was resolved first, before we combine too many changes together. 😄 

[Version_Control_SanitizeColors_Beta.zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/6610937/Version_Control_SanitizeColors_Beta.zip)

If we can do some testing with this, and verify that the colors are coming through correctly for our projects, we can get this merged into `dev` and see if we can wrap up the 3.4.0 release.

**Comment by A9G-Data-Droid** [comment]
Completed in 36.75 seconds with tons of changes. Looks like some XML formatting, the final line of each file has a newline, and the colors are being stripped. So that's all good.

**Comment by A9G-Data-Droid** [comment]
When I went to build from this full export I ended up in an unfamiliar place:

![image](https://user-images.githubusercontent.com/26984068/121067512-00e9dd80-c780-11eb-9050-42249a9a4342.png)

**Comment by A9G-Data-Droid** [comment]
After a quick browse through my forms the colors did not survive the round trip. Some background colors were lost, namely headers, and buttons. The Foreground text has also defaulted on many controls. Doesn't look good.

**Comment by hecon5** [comment]
I have often seen that right after build. If I close/reopen access, they appear to be fixed again.

**Comment by joyfullservice** [comment]
> 
> 
> After a quick browse through my forms the colors did not survive the round trip. Some background colors were lost, namely headers, and buttons. The Foreground text has also defaulted on many controls. Doesn't look good.

This is helpful feedback. It sounds like there are a few kinks that need to be worked out, probably relating to how Access handles the implied color/theme defaults on controls. Perhaps I will make a form in the testing database that I can use to verify different combinations of control types and color settings....

**Comment by joyfullservice** [comment]
I added a form to the testing database, and reviewed the `BackColor` property after round trip conversion. Initially the form didn't look right in the rebuilt database, but after reopening the database so the custom theme loaded properly, then it looked just like the original, even after stripping out the dynamic colors in the source files.

![image](https://user-images.githubusercontent.com/7254992/121077901-d60e8200-c79d-11eb-88fb-a59a8ebd58fd.png)

Are you able to pinpoint some specifics about which controls/colors did not come through correctly? I did notice that I need to extend my range of system color constants to include a list of theme colors. (I will be pushing that commit shortly) I am not sure if this is related to what you were seeing in your database, or if it is something else.

**Comment by A9G-Data-Droid** [comment]
So the `Form Header` had a specific defined `Back Color`, not a theme. The rebuilt DB it is set to white #FFFFFF

The label text `Fore Color` was set to `Text Light` which appears white. The rebuilt DB has all text set to black #000000

I have reopened it multiple times. I have gone to designer mode to inspect the color value. It remains these default values.

**Comment by joyfullservice** [comment]
I just added exceptions for the form header and footer to be treated the same as other form detail sections. I believe that will fix the header color issue.

For the label `Fore Color`, that sounds like it was resolved in 3e4167e where any negative color number is now treated as a constant. (Instead of the initial approach of using the (incomplete) range of VBA.SystemColorConstants

Would you be able to build the `SanitizeDynamicThemeColors` branch and try again with the latest commits? It sounds like we may be getting close!

**Comment by A9G-Data-Droid** [comment]
Good news! The new version of VCS was able to build itself so that workflow is back for me.

I saw Form header and footer BackColor in my diff. As well as BorderColor, ForeColor, and GridlineColor! 

After looking through my forms the only thing that jumps out at me is a button that is using a theme color `Background 2, Darker 50%`. It's showing up as a different color despite the BackColor value looking to be the same. This is because my main "Theme" itself has been set back to the default "Office Theme used by Database". It looks like my custom theme got it's name saved as the default name at some point. If I save the theme with a distinct name then it gets exported properly.

Then, something completely unacceptable happened. I am now seeing strange data showing up in the `FontName` field. 

I saw this in my diff:

-                    FontName ="Segoe UI"
+                    FontName ="Segoe UIustomerName]; \";\"Custom"

This is repeated on multiple controls across all my forms. The data showing up in the FontName is found elsewhere in the form. Something terrible is happening with the text buffer maybe?

**Comment by joyfullservice** [comment]
@A9G-Data-Droid - Great to hear that the colors are coming through correctly!

The text buffer issue looks rather bizarre... It is using the concatenation class to build the output for the file, but it has been doing that for a long time without issues. Does it only happen with the font names? Perhaps some string pointer corruption issue? What happens if you close all instances of Access, [decompile](http://www.fmsinc.com/microsoftaccess/performance/decompile.asp) the database, compile, save, and try again? I have personally never seen that happen before...

You might also try a `SaveAsText` call from the immediate window to see if the problem is happening in the initial export of the form, or when it is being sanitized by the add-in.

**Comment by A9G-Data-Droid** [comment]
I think I have found the issue. It's a combination of the fact that long lines are split in to multiple lines and sanitize is removing only the first line of a multi line string.

In my case, I have a combobox with a `BaseInfo=` property that is wrapped in two lines. BaseInfo comes right after `FontName` so there is some leftover junk after the FontName. When you run a build, this extra line is injected in to the FontName because it now appears to be the 2nd line of the FontName property. This will be seen on subsequent exports.

So we need to fix how sanitize is removing multiline BaseInfo property.

**Comment by A9G-Data-Droid** [comment]
From this I can tell you are checking the `lngLine + 1` but then you skip just lngLine, off by one error. I think you need to add one to the line you are skipping too.

Like this:

                        Do While GetIndent(varLines(lngLine + 1)) > intIndent
                            ' Skip and move to next line
                            SkipLine lngLine + 1
                            lngLine = lngLine + 1
                        Loop

**Comment by joyfullservice** [comment]
Nice catch! How do things look after implementing that?

**Comment by joyfullservice** [comment]
If we are pretty satisfied with the results of the color sanitizing, I would like to merge this over to `dev` so we can switch to the `*.cls` file extension for the class modules. Right now these two branches use different output file names, so you have to use a different add-in to build each branch, which gets complicated when I am jumping back and forth between the branches.  😄  I just didn't want to dump all those changes into the mix while we were still making sure the color sanitizing was going to work.

With the updates today, and the additional testing we have done on our databases, I am thinking we should be pretty safe to move forward with this approach of sanitizing the color values. We can always make little tweaks and bug fixes going forward, but the overall concept seems to be working pretty effectively.

**Comment by A9G-Data-Droid** [comment]
Ok, I did an Export, Build, Export.

I can see the Theme information being lost now. My custom theme was in the first export but not the second. 

This does cause colors to be different in the built DB.

There are other strange differences not related to theme or color that I don't understand.

**Comment by joyfullservice** [comment]
Update: I have merged `SanitizeDynamicThemeColors` into `dev` for ongoing development. Below is a copy of the latest `dev` version which can be used to build the `dev` branch. (The `dev` branch will become the 3.4.x release when stable.)
[Version_Control_v3.4.1.zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/6612716/Version_Control_v3.4.1.zip)

**Comment by joyfullservice** [comment]
Thanks for posting these examples. I will test this when I get back to my computer. Would you also be able to include the relevant sections of the export file? (With aggressive sanitize off, so I can compare the original color information.) Thanks!

**Comment by hecon5** [comment]
Sure thing:

3.4.1 Export (Aggressive Sanitize off), controls as shown above:
```DIFF
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    TextFontFamily =34
                    Left =240
                    Top =180
                    Width =3960
                    Height =450
                    FontSize =18
                    FontWeight =700
                    BorderColor =14261504
                    ForeColor =16777215
                    Name ="Auto_Title0"
                    Caption ="Home Page"
                    FontName ="Calibri"
++                  GUID = Begin
++                      0xaf59f7c088c9574082ade24c08038bc3
++                  End
                    GridlineColor =0
                    LayoutCachedLeft =240
                    LayoutCachedTop =180
                    LayoutCachedWidth =4200
                    LayoutCachedHeight =630
                End


                Begin CommandButton
                    OverlapFlags =85
                    TextFontFamily =34
                    Left =5460
                    Top =1320
                    Width =1800
                    Height =432
                    FontSize =11
                    TabIndex =5
                    ForeColor =0
                    Name ="HelpFilesButton"
                    Caption ="Helpfiles"
                    FontName ="Calibri"
                    ControlTipText ="Quick Guides and Design Manual on SharePoint"
                    HyperlinkAddress ="https://www.hellllllppppmeeeeeee.somethingneat"
++                  GUID = Begin
++                      0x579b7790e24e404380e84248eb4f5369
++                  End
                    LeftPadding =0
                    TopPadding =0
                    BottomPadding =15

                    LayoutCachedLeft =5460
                    LayoutCachedTop =1320
                    LayoutCachedWidth =7260
                    LayoutCachedHeight =1752
                    ForeThemeColorIndex =0
                    UseTheme =1
                    Shape =2
                    Bevel =1
                    BackColor =11193849
                    BorderWidth =1
                    BorderColor =-2147483617
                    HoverColor =8435191
                    PressedColor =2838138
                    HoverForeColor =0
                    PressedForeColor =0
                    SoftEdges =1
                    QuickStyle =1
                    QuickStyleMask =-1024
                    WebImagePaddingRight =1
                End
```

And with Aggressive sanitize on:
```DIFF
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    TextFontFamily =34
                    Left =240
                    Top =180
                    Width =3960
                    Height =450
                    FontSize =18
                    FontWeight =700
--                  BorderColor =14261504
--                  ForeColor =16777215
                    Name ="Auto_Title0"
                    Caption ="Home Page"
                    FontName ="Calibri"
--                  GridlineColor =0
                    LayoutCachedLeft =240
                    LayoutCachedTop =180
                    LayoutCachedWidth =4200
                    LayoutCachedHeight =630
                End

                Begin CommandButton
                    OverlapFlags =85
                    TextFontFamily =34
                    Left =5460
                    Top =1320
                    Width =1800
                    Height =432
                    FontSize =11
                    TabIndex =5
--                  ForeColor =0
                    Name ="HelpFilesButton"
                    Caption ="Helpfiles"
                    FontName ="Calibri"
                    ControlTipText ="Quick Guides and Design Manual on SharePoint"
                    HyperlinkAddress ="https://www.hellllllppppmeeeeeee.somethingneat"
                    LeftPadding =0
                    TopPadding =0
                    BottomPadding =15

                    LayoutCachedLeft =5460
                    LayoutCachedTop =1320
                    LayoutCachedWidth =7260
                    LayoutCachedHeight =1752
                    ForeThemeColorIndex =0
                    UseTheme =1
                    Shape =2
                    Bevel =1
--                  BackColor =11193849
                    BorderWidth =1
                    BorderColor =-2147483617
--                  HoverColor =8435191
--                  PressedColor =2838138
--                  HoverForeColor =0
--                  PressedForeColor =0
                    SoftEdges =1
                    QuickStyle =1
                    QuickStyleMask =-1024
                    WebImagePaddingRight =1
                End

```

**Comment by joyfullservice** [comment]
Okay, after some further testing, I think I know what is going on. I have seen this before in certain situations but for whatever reason, the definition block is incomplete for the control. If I create the control from scratch, using the properties shown in the screenshot above, it creates the full definition block which works perfectly in my testing. (Full round trip produces identical source files with the correct colors.)

To reproduce exactly what you were seeing, I inserted the object definition block provided above into a test form, and imported from source. As you were finding, the colors were lost since the index properties were not included in the source file. When I manually set those colors in the property window and then ran an export, the missing property lines were included in the export file, and the round-trip testing worked perfectly after that.

![image](https://user-images.githubusercontent.com/7254992/121219785-ab7a0300-c849-11eb-8def-9f53f7561dd9.png)

**Comment by A9G-Data-Droid** [comment]
@joyfullservice could this be fixed automatically by setting the value to itself via code?

**Comment by A9G-Data-Droid** [comment]
Ok, that's going to be painfully slow. If we had a function to heal this it would be something to run once per project. Could you detect the condition and ask the user if they want to fix it?

**Comment by joyfullservice** [comment]
Perhaps we should make a `ColorRepair` function that opens each form in design view, loops through all the controls and sets all the color values to ensure that the definition blocks are complete. Like you pointed out, this would only need to be run once per project. My hunch is that this condition occurs when a project is converted from previous database versions, and the control properties are just carried over from what they were before until someone changes one of the properties, triggering a rewrite of the property.

As far as detecting the condition, that might be a little tricky... Hmm... Normally the index would be missing if it was using the default theme color, but that seems a little complicated and potentially risky to try to compute that.

One approach would be to just have the user confirm the colors the first time they build from source. If they see any issues, they could run the color repair on the original database, then do the export again. I would love to automate that verification, but I am not sure of a simple way to do that.

Technically if the user missed something in their initial review, all they have to do is fix the colors where they find the problem, and it will work fine going forward.

**Comment by joyfullservice** [comment]
Here is some simple code demonstrating the concept... What happens if you run it in a copy of your database? How performant is it, and does it resolve the color issues? Seems to work great in my little test...

```
Public Function VerifyColors()

    Dim obj As AccessObject
    Dim prp As AccessObjectProperty
    Dim ctl As Control
    Dim prpCtl As Property
    
    For Each obj In CurrentProject.AllForms
        DoCmd.OpenForm obj.Name, acDesign, , , , acHidden
        For Each ctl In Forms(obj.Name).Controls
            For Each prpCtl In ctl.Properties
                With prpCtl
                    If InStr(1, .Name, "Color", vbTextCompare) > 0 Then
                        .Value = .Value
                    End If
                End With
            Next prpCtl
        Next ctl
        DoCmd.Close acForm, obj.Name, acSaveYes
    Next obj

End Function
```

**Comment by joyfullservice** [comment]
Here is a more comprehensive approach handling forms, sections, and controls. Let me know how this works!

```
Public Function VerifyColors()

    Dim obj As AccessObject
    Dim frm As Form
    Dim ctl As Control
    Dim sec As Section
    Dim intSec As Integer
    
    For Each obj In CurrentProject.AllForms
        DoCmd.OpenForm obj.Name, acDesign, , , , acHidden
        Set frm = Forms(obj.Name)
        
        ' Form properties
        SetColorProperties frm.Properties
        
        ' Control properties
        For Each ctl In frm.Controls
            SetColorProperties ctl.Properties
        Next ctl
        
        ' Section properties (header, detail, footer, etc...)
        For intSec = acDetail To 20 ' Max sections?
            On Error Resume Next
            Set sec = frm.Section(intSec)
            If Err Then
                ' Invalid section
                Err.Clear
            Else
                SetColorProperties sec.Properties
            End If
        Next intSec
        
        ' Save and close form
        DoCmd.Close acForm, obj.Name, acSaveYes
    Next obj

End Function


Private Sub SetColorProperties(prpCollection As Properties)
    Dim prp As Property
    For Each prp In prpCollection
        With prp
            If InStr(1, .Name, "Color", vbTextCompare) > 0 Then
                .Value = .Value
            End If
        End With
    Next prp
End Sub

```

**Comment by joyfullservice** [comment]
Based on my testing, it appears that this issue has been resolved through the enhancement to the sanitize functions. Further bugs/issues in the implementation can be added and tracked as new issues.

With regard to the partial definition blocks in form source files, that is a related, but separate issue, so I will go ahead and create a dedicate issue to track a solution for repairing an existing database.

**Comment by hecon5** [comment]
Testing now, but it definitely is still stripping out colors for defined colors, and the routine above did not fix that; it did take ~3 minutes to run though for my DB.

ran `VerifyColors` > Export>import> reopen and colors are reverted for **ALL** controls. Every one. None survived theme import, even themed controls. The only parts that survived are the header background. Literally every other one set itself to white or black.

**Comment by joyfullservice** [comment]
@hecon5 - Are you able to provide a small sample database file illustrating the issue? I would like to try this on my end as well. I highly doubt that Access is treating the colors differently between our versions, but I am just not seeing what you are describing.

**Comment by hecon5** [comment]
Actually, I think I may know why: `verifyColors` is resetting the actual color. Access is replacing the theme with the now forced color. That's ... not ideal, and is still not adding the requisite `-1` entry...

**Comment by hecon5** [comment]
once that happens, the sanitizer scrubs out the colors (because it thinks it's a theme), and poof: away go the colors.

**Comment by hecon5** [comment]
Example Themed Control, which previously used "theme 3" (a green variation)
![image](https://user-images.githubusercontent.com/54177882/121237491-1b49b700-c865-11eb-9f83-a056836dba0d.png)

After running `VerifyColors`, the color is correct, but it's stripping out the Hover/Pressed colors (this is before export/build):
![image](https://user-images.githubusercontent.com/54177882/121237593-37e5ef00-c865-11eb-8e16-dce450d6486e.png)

Also, headers are being hand-set this way, too. 
Instead of "Theme 1" (blueish), it's now set to a defined color. Why those survive the trip and the controls don't isn't clear.

**Comment by joyfullservice** [comment]
I am working on an updated color repair function now, checking for a theme index value before resetting the color.

**Comment by hecon5** [comment]
Out of curiosity: would it be more efficient to just add in `[PropertyColor]ThemeColorIndex =-1` during sanitize if it's not there instead of a repair function?

**Comment by joyfullservice** [comment]
> 
> 
> Out of curiosity: would it be more efficient to just add in `[PropertyColor]ThemeColorIndex =-1` during sanitize if it's not there instead of a repair function?

Great question! The problem is that we don't know what is _missing_ without iterating through the objects themselves. Access has a (binary?) representation of the object that gets pushed out to the export file, but the problem is in the binary storage of the object.

**Comment by hecon5** [comment]
I'll

> You might set an absolute color value to the same color that the theme was using. The object will be the same color, but it is the presence of the index, shade and tint that makes it a theme color instead of an absolute color. The updated repair function will check and enforce all three of these objects for theme colors, so that _should_ fix the issue, providing the original database is using the theme colors, not absolute colors.

Well, that's kind of what spurred it: assume they're absolute values until proven otherwise (system/theme/etc.). Wouldn't require us to handle the host database at all, just the files; and (personally) I'd rather have a bit of noise than have to know I need to run a repair tool. 

I'll rebuild a good version of the database I have been testing on and report back shortly.

**Comment by joyfullservice** [comment]
I just pushed an update to `dev` that I believe will correctly handle the theme color properties, rather than resetting them all to absolute color values.

**Comment by joyfullservice** [comment]
If sanitizing color values commonly requires an initial repair, or tends to be a little problematic for new users, **perhaps it should be its own option** in settings, and off by default. This would make it available to anyone who would like to use it. (I foresee using it in my projects.) But it wouldn't give new users a bad experience if their project happened to contain incomplete object definitions. 🤔

**Comment by hecon5** [comment]
> If sanitizing color values commonly requires an initial repair, or tends to be a little problematic for new users, **perhaps it should be its own option** in settings, and off by default. This would make it available to anyone who would like to use it. (I foresee using it in my projects.) But it wouldn't give new users a bad experience if their project happened to contain incomplete object definitions. 🤔

This is how I think it should work, not just because it's a fairly significant amount of code we're removing from the source files that is a little bit more than noise. I, too, will be implementing this, but I'm definitely closer to the "tries out features maybe before they're always ready" crowd than maybe I should be...

In any case, I'll give the updates a go and try. It may be tomorrow before I reply back, I've got some other things that just lit up on my desk for a moment.

**Comment by joyfullservice** [comment]
> 
> 
> I am unable to build the `dev` branch using the 3.3.17 or 3.4.0 versions I have.

You should be able to build it from [3.4.1](https://github.com/joyfullservice/msaccess-vcs-integration/issues/183#issuecomment-856356566).

**Comment by hecon5** [comment]
More thoughts I've been cogitating on today and last night while sitting in waiting areas: We should have "levels" of color sanitize aggressiveness, (off / robust / aggressive). This could allow us to give most users ability to tune to their desired "noise" level. 

I think we've got good evidence themed controls sanitize properly (that part seems to be consistent and robust), as do the ones where the theme is set to `-1`, but less so where the theme data isn't present at all.

It would also allow us to test and improve the helper routine as well as sanitizing for the edge cases ("Access laziness") and then if we determine we're able to detect and remove hard set values where the theme insert didn't work properly, we can do so then.

I hate code noise as a developer. Especially in Git, and VBA has a tooooon of these issues.  If we can remove even 10% of color noise, it'll make a huge difference to me. It makes me panic a little bit every time I see a lot of forms exported that didn't get work done, and adds work to my workflow. Annoying.

**BUT** I'm dead set against features we aren't *sure* are going to work upon rebuild. The most annoying bugs to troubleshoot for users are ones on forms/code I didn't change in [insert long time here]. I have a few persnickety users who notice (and "ask" me) whenever colors change slightly, and it's annoying to figure out what happened (history, it's been mostly my own fault upon rebuild). I really really really do not want to deal with this addin helping me there.

That said, and "in between " option would make my life so much better. It's reliable (for themed controls, I didn't notice any issues at all). It would also encourage me to use themes for new content, and eventually go back and set themes for old components (which also has the upside of making UI color changing a LOT easier when the powers that be decide to change the app color requirements...again.). 

I like the idea of a "repair" helper function, but it's too "new" to run on some of the larger tools I have right now. But I also very much want to cut out noise on exports for 90% of my forms. Which is why I'd like something in between all or nothing with colors.

So, with all that, I am in favor of a 3 level option, strongly.

**Comment by hecon5** [comment]
![image](https://user-images.githubusercontent.com/54177882/121420340-f162c400-c93a-11eb-804f-31cd78e2bacf.png)

Mocked up how this might work.

**Comment by hecon5** [comment]
![image](https://user-images.githubusercontent.com/54177882/121422215-fcb6ef00-c93c-11eb-942f-1155c5844c1d.png)

Now maps correctly to the sanitize level setting. :)

**Comment by hecon5** [comment]
Ok, testing this on some dbs that lost colors previously; let's see what happens! 

Initial export using `eSanitizeLevel` of `eslRobust` led to most colors where themed being correctly removed. Rebuild looks ok at first glance.

Initial export using `eSanitizeLevel` of `eslToTheBoneBeta` led to the extra fields being removed that caused me issues before. 

If we add the helper routine @joyfullservice added, perhaps if `eslAgressive`or `eslToTheBoneBeta` is chosen a button is exposed to allow you to click it and 'repair' your controls?

**Comment by joyfullservice** [comment]
@hecon5 - Thanks for your work on fleshing this out! Just to clarify, are there problems (VCS noise) that `eslToTheBoneBeta` fixed that were _not_ fixed by `eslAgressive`? In other words, is there a real use-case for the most extreme level of sanitizing color values?

**Comment by hecon5** [comment]
I think, for me, I have way too many controls that are stripped bare and don't have colors (ported from legacy versions) that use hand-set colors that don't rebuild correctly. 

I think some users may benefit from it, and if all my controls were changed to themed controls (eventually), then the to the bone level would be nice. For now, it's not always predictable as to what's not going to work with the sanitize routines I set to 'esltothebonebeta'.

If we can figure that out, we could set those lower, but for now, they are way too aggressive for a reliable rebuild in my environment.

**Comment by hecon5** [comment]
In any regard, I think having levels would allow us to also tune things and introduce features that can be vetted on small databases first, or big ones, as you could just see what changes with the export without redeploying a new addin during testing.

**Comment by A9G-Data-Droid** [comment]
Are custom themes supported? Currently, my custom theme is not being restored or set. I have to set my theme after each rebuild to get my colors back.

**Comment by joyfullservice** [comment]
> 
> 
> Are custom themes supported? Currently, my custom theme is not being restored or set. I have to set my theme after each rebuild to get my colors back.

Yes, custom themes should be supported. Go ahead and open a new issue for this with some details, and let's work to get that fixed.  😄

**Comment by hecon5** [comment]
With the levels implemented, and the error prone sanitization routines in the beta level, theme colors import properly, as do manually set colors. I'm going to do some more testing, but I think this can be closed.

**Comment by hecon5** [comment]
Nevermind, still having some odd behavior where themes are sometimes not set correctly; troubleshooting now.

**Comment by hecon5** [comment]
Full round trip on my more complex database appears to work!

**Comment by hecon5** [comment]
@A9G-Data-Droid, if your testing comes up good, I think we're ready to close this.

**Comment by A9G-Data-Droid** [comment]
I'm seeing some random color change noise using the `dev` branch version `3.4.5`

I have the `Sanitize Colors` set to `Aggressive`

I see these ones changing on most forms:

![image](https://user-images.githubusercontent.com/26984068/123491412-76044200-d5cb-11eb-90c9-5f3c149ae29a.png)

**Comment by joyfullservice** [comment]
Would you be able to expand that to show the whole block? (For example, I am wondering if the `PressedThemeColorIndex` property is shown below the screenshot.)

You could also try the `Advanced (Beta)` option to see how your database handles it. (That assumes more defaults to accommodate incomplete block structures.) At present, the only difference between this and `Aggressive` is that `Advanced (Beta)` removes color values when the `ThemeColorIndex` property is not found.

The following code snippet comes from `modSanitize`:

```vba
    ' Loop through properties, checking for index
    For intCnt = 0 To UBound(varBase)
        strKey = varBase(intCnt) & "ThemeColorIndex"
        If dBlock.Exists(strKey) Then
            If dBlock(strKey) <> NO_THEME_INDEX Then
                ' Check for corresponding color property
                strKey = varBase(intCnt) & "Color"
                If dBlock.Exists(strKey) Then
                    ' Skip the dynamic color line
                    SkipLine dBlock(strKey)
                End If
            End If
        Else
            Select Case dBlock("Type")
                Case "Section", "FormHeader", "FormFooter"
                    ' Some controls like form sections don't use color values
                    ' if a theme index is specified. If a color value exists,
                    ' we should preserve it.
                Case Else
                    ' Most controls automatically use theme indexes
                    ' unless otherwise specified.
                    ' As discussed in #183, this can be affected by incomplete
                    ' component definition blocks.
                    If Options.SanitizeColors = eslAdvancedBeta Then
                        strKey = varBase(intCnt) & "Color"
                        If dBlock.Exists(strKey) Then
                            ' Skip the dynamic color line
                            SkipLine dBlock(strKey)
                        End If
                    End If
            End Select
        End If
    Next intCnt
```

**Comment by joyfullservice** [comment]
@A9G-Data-Droid - Is this working on the latest build (3.4.13) from the `dev` branch? Between the sanitize updates and initializing forms I think this might be resolved now. Would you be able to verify this so we can close out this issue?

**Comment by A9G-Data-Droid** [comment]
Ok, I did the full round trip on my main project DB. I'm seeing the same color noise as before (BackColor, HoverColor, and PressedColor). Honestly, it's not a show stopper. I wouldn't let this issue hold up 3.4 release. 

When I run with "Advanced (Beta)" it does remove a few color lines, including the noisy ones. This doesn't seem to be destructive with my project. The built and rebuilt versions are stable. Colors look correct. When I use this advanced sanitation profile this issue is completely resolved.

**Comment by hecon5** [comment]
Huzzah!

**Comment by joyfullservice** [comment]
Awesome! From the best that I understand, the "_Advanced (Beta)_" seems to be needed in limited cases where the form block structures are not fully complete. Thanks again for letting us know how it went on your project database!
