### ISSUE TITLE
Turkish (Unicode) character problem in JSON conversion

### ISSUE THREAD

**Issue by kocivan** [joyfullservice/msaccess-vcs-integration#30]
Hi,
The problem with my other question continues. There are also problems with Turkish characters.
![2020-05-24 (4)](https://user-images.githubusercontent.com/65854444/82757766-4e044700-9deb-11ea-8111-44454ce43015.png)

**Comment by cenx1** [comment]
It is not only Turkish characters. Danish characters (ÆØÅ) is also a problem. 

From my quick inspection it looks like the issue is in multiple places:
- The __modJsonConverter__-->__json_Encode__ function. All characters with char code above 127 are handled incorrect:
```vb
Select Case json_AscCode
        Case 34
            ' " -> 34 -> \"
            json_Char = "\"""
        Case 92
            ' \ -> 92 -> \\
            json_Char = "\\"
        Case 47
            ' / -> 47 -> \/ (optional)
            If JsonOptions.EscapeSolidus Then
                json_Char = "\/"
            End If
        Case 8
            ' backspace -> 8 -> \b
            json_Char = "\b"
        Case 12
            ' form feed -> 12 -> \f
            json_Char = "\f"
        Case 10
            ' line feed -> 10 -> \n
            json_Char = "\n"
        Case 13
            ' carriage return -> 13 -> \r
            json_Char = "\r"
        Case 9
            ' tab -> 9 -> \t
            json_Char = "\t"
        Case 0 To 31, 127 To 65535
            ' Non-ascii characters -> convert to 4-digit hex
            json_Char = "\u" & VBA.Right$("0000" & VBA.Hex$(json_AscCode), 4)
        End Select
```

I don't know what the solution should be right now. For my self I have added the cases for the foreign characters that I need (ÆØÅ )
-  The __modFunctions__ --> __SanitizeFile__ function writes the sanitized output to file __after__ it has been converted to UT8. 
My suggestion for fixing this is to have the `ConvertUcs2Utf8 strTempFile, strFile` instruction at the end of the `SaveComponentAsText` function:
```vb
Public Sub SaveComponentAsText(intType As AcObjectType, strName As String, strFile As String)
    
    Dim strTempFile As String
    
    ' Make sure the path exists before we write a file.
    VerifyPath FSO.GetParentFolderName(strFile)
        
    ' Export to temporary file
    strTempFile = GetTempFile
    Application.SaveAsText intType, strName, strTempFile
           
    ' Sanitize certain object types
    Select Case intType
        Case acForm, acReport, acQuery, acMacro
            Debug.Print "No Sanitize file: " & strFile
            'SanitizeFile strFile
    End Select
       
    ' Handle UCS conversion if needed
    ConvertUcs2Utf8 strTempFile, strFile
    
End Sub
```

**Comment by joyfullservice** [comment]
This modJsonConverter comes from the https://github.com/VBA-tools/VBA-JSON project. It looks like there are a number of issues and pull requests on that code base, and other forks that might possibly address the Unicode issues...

From my perspective, I would actually prefer to keep the Unicode text as nice readable Unicode text in the export files. (That is the most helpful for someone reviewing source code in Git.) If someone would like to update this module and submit a pull request to retain the Unicode text, I would be happy to review and merge this into the core.

If we are also seeing issues with the sanitization process as @cenx1 described, I suggest that we split that into a separate issue, since it involves a different set of code.

Thanks again for the input and suggestions! I think that resolving these issues should be a great help for anyone that is using this tool with Unicode character sets!

**Comment by joyfullservice** [comment]
Looks like this might be as simple as just not escaping the Unicode characters...  https://github.com/VBA-tools/VBA-JSON/issues/37

**Comment by joyfullservice** [comment]
The JSON portion of this issue should be fixed now in v3.1.8. Let me know how this works, since I obviously wasn't testing with Turkish or Danish text.  😄

**Comment by joyfullservice** [comment]
I also added a pull request to https://github.com/VBA-tools/VBA-JSON/issues/37, so hopefully those changes will also be merged into the upstream master for the JSON conversion.

**Comment by kocivan** [comment]
Mr. @joyfullservice 
Sorry, the problem persists.
Trial result with 31.8 versions
![2020-05-26 (2)](https://user-images.githubusercontent.com/65854444/82846632-7fb40580-9ef2-11ea-9635-f0716641471c.png)

**Comment by joyfullservice** [comment]
@kocivan - Please give this a try after installing the latest version v3.1.26, and let me know if it resolves the issue for you!
